#!groovy

// Generated by IBM TransformationAdvisor
// Tue Jun 25 23:44:39 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'plantsbywebspherev8'
    mvnCommands = '--version'
    test='false'
}